// Test environment setup — provide minimal valid env before any module imports
process.env['NODE_ENV'] = 'test'
process.env['TENANT_KEY'] = 'test-school'
process.env['TENANT_NAME'] = 'Test School'
process.env['DATABASE_URL'] = 'postgresql://postgres:postgres@localhost:5432/astra_test'
process.env['S3_ENDPOINT'] = 'http://localhost:9000'
process.env['S3_ACCESS_KEY_ID'] = 'test-access-key'
process.env['S3_SECRET_ACCESS_KEY'] = 'test-secret-key'
process.env['S3_BUCKET_AVATARS'] = 'avatars'
process.env['S3_BUCKET_PERMITS'] = 'perizinan'
process.env['OIDC_JWT_SECRET'] = 'test-jwt-secret-that-is-long-enough-32-chars'
process.env['OIDC_ISSUER'] = 'https://auth.school.test'
process.env['OIDC_AUDIENCE'] = 'authenticated'
process.env['ROBIN_BASE_URL'] = 'http://localhost:8000'
process.env['ROBIN_ENROLL_STATUS_TIMEOUT_MS'] = '5000'
process.env['DB_QUERY_TIMEOUT_MS'] = '5000'
process.env['STORAGE_UPLOAD_TIMEOUT_MS'] = '15000'
