apiVersion: v1
kind: Secret
metadata:
  name: project-astra-secrets
  labels:
    app.kubernetes.io/name: project-astra
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:password@pgbouncer.default.svc.cluster.local:6432/astra
  S3_ACCESS_KEY_ID: replace-me-s3-access-key
  S3_SECRET_ACCESS_KEY: replace-me-s3-secret-key
  OIDC_JWT_SECRET: replace-me-if-using-shared-secret
  REDIS_URL: redis://default:password@redis.default.svc.cluster.local:6379
